CC=gcc
CFLAGS = -o

all: clean part1a part1b part2 progb

part1a:
	$(CC) -o part1a part1a.c 

part1b:
	$(CC) -o part1b part1b.c 

part2:
	$(CC) -o part2 part2.c
  
progb:
	$(CC) -o progb progb.c 
  
clean:
	rm part1a
	rm part1b
	rm part2
	rm progb
